version: "3.7"
services:
  # 開発環境
  develop:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/develop/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio-access-key
      AWS_SECRET_ACCESS_KEY: minio-secret-key
    shm_size: "2gb"
    tty: true
    volumes:
      - .:/home/dev/pl-image-classification
      - ~/.ssh:/home/dev/.ssh

  # MLFlow
  mlflow:
    restart: always
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio-access-key
      AWS_SECRET_ACCESS_KEY: minio-secret-key
    depends_on:
      - postgresql
      - minio
    ports:
        - "5000:5000"
    command: >
      mlflow server
        --backend-store-uri postgresql+psycopg2://postgre:postgre@postgresql:5432/mlflow-db
        --default-artifact-root s3://default/
        --host 0.0.0.0
        --port 5000
  postgresql:
    image: postgres:12.4
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always
    # volumes:
    #  - "./postgres_data/data:/var/lib/postgresql/data"
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
    command: server /export
  defaultbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio-access-key minio-secret-key)
      do echo 'try to create buckets...' && sleep 1; done;
      /usr/bin/mc mb myminio/default;
      /usr/bin/mc policy download myminio/default;
      exit 0;
      "
