version: "3.7"
services:
  # 開発環境
  develop:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/develop/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    shm_size: "2gb"
    tty: true
    volumes:
      - .:/home/dev/pl-image-classification
      - ~/.ssh:/home/dev/.ssh

  # MLFlow
  mlflow:
    env_file:
      - .env
    restart: always
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    image: mlflow
    depends_on:
      - postgresql
      - minio
    ports:
        - "5000:5000"
    command: >
      mlflow server
        --backend-store-uri postgresql+psycopg2://postgre:postgre@postgresql:5432/mlflow-db
        --default-artifact-root s3://default/
        --host 0.0.0.0
        --port 5000
  postgresql:
    image: postgres:12.4
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: mlflow-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgresql
    restart: always
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    restart: always
    command: server /export
  defaultbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio-access-key minio-secret-key)
      do echo 'try to create buckets...' && sleep 1; done;
      /usr/bin/mc mb myminio/default;
      /usr/bin/mc policy download myminio/default;
      exit 0;
      "
