defaults:
  - hydra: default
  - server: default
  - transform.train: train_default
  - transform.train: val_default

general:
  seed: 57
  epoch: 500
  gpus: [0]
  precision: 16
  amp_backend: "native" # [native or apex]
  amp_level: O2
  accelerator: null # [dp, ddp, ddp_cpu or ddp2]
  acc_grad: 1
  deterministic: True
  debug: False
  resume_from_checkpoint: null

callback:
  checkpoint:
    monitor: val_loss_mean
    save_last: True
    save_top_k: 1
    mode: min
    save_weights_only: True
    filename: "{epoch}-{val_loss_mean:.3f}-{val_acc:.3f}.pth"

data:
  dataset:
    root: ../data/CIFAR10/train
    k_fold: 20
    val_k: 0
  dataloader:
    batch_size: 128
    num_workers: 4
    shuffle: True
    pin_memory: True

model:
  base: timm
  model_name: tf_efficientnet_b4
  pretrained: True
  num_classes: 10
  in_chans: 3
  drop_rate: 0.3

loss:
  base: torch
  name: cross_entropy

optimizer:
  optimizer:
    optim_name: RAdam
    params:
      lr: !!float 1e-5
  scheduler:
    name: CosineAnnealingWarmUpRestarts
    params:
      T_0: 500
      T_mult: 1
      eta_max: !!float 1e-3
      T_up: 10
      gamma: 0.8
