# @package _group_
train:
  name: Compose
  params: 
    - name: PadIfNeeded
      params: 
        min_height: 36
        min_width: 36
    - name: RandomCrop
      params: 
        height: 32
        width: 32
    - name: HorizontalFlip
    - name: Normalize
      params: 
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - name: ToTensorV2
val:
  name: Compose
  params: 
    - name: Normalize
      params: 
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - name: ToTensorV2
